export const LocatorsConstant={
    //CommonPage Locator Identifier:
    "TagWithAttribute":"commonPage.pageObject.tagWithAttribute",
    "ButtonWithText":"commonPage.pageObject.buttonWithText",
    "TagWithText":"commonPage.pageObject.tagWithText",
    "TagWithExactText":"commonPage.pageObject.tagWithExactText",
    "MenuBarOption":"commonPage.pageObject.menuBarOption",
    "TabControl":"commonPage.pageObject.tabControl",
    "TagWithPartialAttribute":"commonPage.pageObject.tagWithPartialAttribute",
    "TextField":"commonPage.pageObject.textField",
    "DialogMainViewElementText":"commonPage.pageObject.dialogMainViewElementText",
    "DialogMainViewElementTextWithContains":"commonPage.pageObject.dialogMainViewElementTextWithContains",
    "DialogMainViewElementAttribute":"commonPage.pageObject.dialogMainViewElementAttribute",
    "PopUpMessageText":"commonPage.pageObject.popUpMessageText",
    "ComboboxDropdownOptionWithEcparentcomp":"commonPage.pageObject.comboboxDropdownOptionWithEcparentcomp",
    "DropdownOptionWithFieldName":"commonPage.pageObject.dropdownOptionWithFieldName",
    "FormFieldWithIcon":"commonPage.pageObject.formFieldWithIcon",
    "CheckBoxOrRadioButtonField":"commonPage.pageObject.checkBoxOrRadioButtonField",
    "RadioButtonWithFieldName":"commonPage.pageObject.radioButtonWithFieldName",
    "MenuBar":"commonPage.pageObject.menuBar",
    "SubMenuBar":"commonPage.pageObject.subMenuBar",
    "TableCellValue":"commonPage.pageObject.tableCellValue",
    "AnyFieldWithFormLabel": "commonPage.pageObject.anyFieldWithFormLabel",
    "Spinner": "commonPage.pageObject.spinner",
    "IFrameWorkFlow": "commonPage.pageObject.iFrameWorkFlow",
    "SelectedOption" : "commonPage.pageObject.selectedOption",
};