# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
name: 'Smoke Suite-$(Date:yyyyMMdd)$(Rev:.r)'

trigger:
- none
pool:
  vmImage: windows-latest

steps:
- checkout: self
  persistCredentials: true
  displayName: 'Checking out code'
 
- task: npmAuthenticate@0
  displayName: 'npm Authenticate .npmrc'
  inputs:
      workingFile: './CatWebLimsAutomation/.npmrc'
      customEndpoint: 'NPM Artifactory'
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'
- script: |
    cd CatWebLimsAutomation
    npm install
  displayName: 'Install dependencies'

- script: |
    npx playwright install
  displayName: 'Install Playwright browsers'

- script: |
    cd CatWebLimsAutomation
    npm run Smoke
  displayName: 'Executing Smoke Test'
  continueOnError: true
  
- script: |
    cd CatWebLimsAutomation
    npm run build
  displayName: 'Generating Cucumber HTML Report'
- task: CopyFiles@1
  inputs:
   SourceFolder: 'CatWebLimsAutomation/reports'
   TargetFolder: '$(Build.ArtifactStagingDirectory)/test-results/Smoke'   

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/test-results/Smoke'
    artifact: 'Smoke_Result'